import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:hexcolor/hexcolor.dart';
import 'package:intl/intl.dart';
import 'package:kwik_port/api/model/dashboard_model.dart';
import 'package:kwik_port/api/utils/money_util.dart';
import 'package:kwik_port/colors/color.dart';
import 'package:kwik_port/main.dart';
import 'package:kwik_port/ui/home/kwikticket/kwikticket_screen.dart';
import 'package:kwik_port/ui/home/dashboard/dashboard.dart';
import 'package:kwik_port/ui/home/kwikticket/save_pending_ticket.dart';
import 'package:kwik_port/utils/button/backNav_button.dart';
import 'package:kwik_port/utils/button/bottom_navigatior_bar.dart';
import 'package:kwik_port/utils/button/kwik_button.dart';
import 'package:kwik_port/utils/text/contract_detail_heading_and_subtitle.dart';
import 'package:kwik_port/utils/text/textstyle.dart';
import 'package:kwik_port/utils/toast.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:permission_handler/permission_handler.dart';

class KwikticketCreatedSuccessfully extends StatefulWidget {
  final KwikTicketModel kwikticket;

  // final kwikticketID,
  // exporterName,
  // exportItem,
  // contractType,
  // stakedVolume,
  // capitalCost,
  // destination;
  const KwikticketCreatedSuccessfully({super.key, required this.kwikticket});

  @override
  State<KwikticketCreatedSuccessfully> createState() =>
      _KwikticketCreatedSuccessfullyState();
}

class _KwikticketCreatedSuccessfullyState
    extends State<KwikticketCreatedSuccessfully> {
  @override
  void initState() {
    super.initState();
    savePendingTicket(widget.kwikticket.uniqueId!);
  }

  Future<void> _downloadReceipt(context) async {
    try {
      // Generate PDF
      final pdf = pw.Document();
      
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Container(
              padding: const pw.EdgeInsets.all(40),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Center(
                    child: pw.Text(
                      'KwikTicket',
                      style: pw.TextStyle(
                        fontSize: 32,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ),
                  pw.SizedBox(height: 30),
                  pw.Divider(),
                  pw.SizedBox(height: 20),
                  _buildPdfRow('Kwikticket ID', widget.kwikticket.uniqueId ?? 'N/A'),
                  pw.SizedBox(height: 15),
                  _buildPdfRow('Exporter Name', widget.kwikticket.exporter?.businessName ?? 'N/A'),
                  pw.SizedBox(height: 15),
                  _buildPdfRow('Export Item', widget.kwikticket.contract?.commodityName ?? 'N/A'),
                  pw.SizedBox(height: 15),
                  _buildPdfRow('Contract Type', 
                    widget.kwikticket.contract?.contractType == 1 ? 'International Buyer' : 'Local Buyer'),
                  pw.SizedBox(height: 15),
                  _buildPdfRow('Selected Capacity', '${widget.kwikticket.quantityToFulfill ?? 0} tons'),
                  pw.SizedBox(height: 15),
                  _buildPdfRow('Commodity Cost', 
                    MoneyUtils.formatMoney(widget.kwikticket.kwikTicketAmount ?? 0)),
                  pw.SizedBox(height: 15),
                  _buildPdfRow('Buyer Price Per Ton', 
                    '\u20a6${NumberFormat('#,##0.00').format(widget.kwikticket.contract?.buyerSpecification?.buyerPricePerUnit ?? 0)}'),
                  pw.SizedBox(height: 15),
                  _buildPdfRow('Export Gross Earning', 
                    '\u20a6${NumberFormat('#,##0.00').format(widget.kwikticket.projectedIncomeInDollars ?? 0)}'),
                  pw.SizedBox(height: 15),
                  _buildPdfRow('Destination', widget.kwikticket.contract?.destinationCountry ?? 'N/A'),
                  pw.SizedBox(height: 15),
                  _buildPdfRow('Created Date', 
                    DateFormat('dd MMM yyyy').format(widget.kwikticket.createdAt ?? DateTime.now())),
                  pw.SizedBox(height: 30),
                  pw.Divider(),
                  pw.SizedBox(height: 20),
                  pw.Center(
                    child: pw.Text(
                      'Generated by KwikPort',
                      style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
                    ),
                  ),
                ],
              ),
            );
          },
        ),
      );

      // Share the PDF
      await Printing.sharePdf(
        bytes: await pdf.save(),
        filename: 'kwikTicket_${DateTime.now().millisecondsSinceEpoch}.pdf',
      );

      showToastContainer(
        "Success",
        "KwikTicket PDF generated successfully",
        colorCodes.mediumSeaGreen,
        colorCodes.pigmentGreen,
        context,
      );
    } catch (e) {
      showToastContainer(
        "Error",
        "Failed to generate PDF: ${e.toString()}",
        colorCodes.mistyRose,
        colorCodes.portlandOrange,
        context,
      );
    }
  }

  pw.Widget _buildPdfRow(String label, String value) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          label,
          style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
        ),
        pw.Text(
          value,
          style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
        ),
      ],
    );
  }

  Future saveImage(Uint8List bytes) async {
    final appStorage = await getApplicationDocumentsDirectory();
    File file = File('${appStorage.path}/xchangReceipt.png');
    file.writeAsBytes(bytes);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBody: true,
      backgroundColor: colorCodes.whiteSmoke,
      body: ListView(
        padding: EdgeInsets.symmetric(horizontal: 20, vertical: 40),
        children: [
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Align(
                alignment: Alignment.centerLeft,
                child: backnavButton(
                  context,
                  func: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => Dashboard()),
                    );
                    currentIndex = 1;
                  },
                ),
              ),
              SizedBox(height: 15),
              Image.asset(
                'assets/images/icons/ticket_generate_success.png',
                height: 96,
                width: 113,
              ),
              SizedBox(height: 40),
              Text(
                "Kwikticket generated successfully",
                style: kwikTextStlye(24.0, FontWeight.w600, colorCodes.black),
                textAlign: TextAlign.center,
              ),
              SizedBox(height: 21),
              Container(
                height: 45,
                width: 300,
                alignment: Alignment.center,
                padding: EdgeInsets.symmetric(horizontal: 10, vertical: 10),
                decoration: BoxDecoration(
                  color: colorCodes.white,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(
                    width: 1.5,
                    color: colorCodes.paleCornflowerBlue,
                  ),
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Image.asset(
                      "assets/images/icons/dashboard/kwikticket_blue.png",
                      height: 25,
                      width: 25,
                    ),
                    SizedBox(width: 6),
                    SizedBox(
                      width: 242,
                      child: Text(
                        "This is your personalised contract offer.",
                        style: kwikTextStlye(
                          12.0,
                          FontWeight.w300,
                          colorCodes.jetBlack,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              SizedBox(height: 24),
              Container(
                height: 395,
                width: 390,
                padding: const EdgeInsets.symmetric(
                  horizontal: 24,
                  vertical: 24,
                ),
                decoration: BoxDecoration(
                  border: Border.all(
                    width: 1.2,
                    color: colorCodes.antiFlashWhite,
                  ),
                  borderRadius: BorderRadius.circular(16),
                  color: colorCodes.white,
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    contractDetailHeadingAndSubtitletwo(
                      "Kwikticket ID",
                      "Exporter Name",
                      widget.kwikticket.uniqueId,
                      widget.kwikticket.exporter?.businessName,
                      // "#Kwk-8989-09",
                      // "John  Gbenga",
                    ),
                    SizedBox(height: 20),
                    contractDetailHeadingAndSubtitletwo(
                      "Export Item",
                      "Contract type",
                      widget.kwikticket.contract?.commodityName,
                      widget.kwikticket.contract?.contractType == 1
                          ? "International Buyer"
                          : "Local Buyer",

                      // "Cocoa bean",
                      // "Agricultural Commodity",
                    ),
                    SizedBox(height: 20),
                    contractDetailHeadingAndSubtitletwo(
                      "Selected Capacity",
                      "Commodity Cost",
                      "${widget.kwikticket.quantityToFulfill} tons",
                      "${MoneyUtils.formatMoney(widget.kwikticket.kwikTicketAmount?.toString() ?? '0')}",
                      // "20.5 tons",
                      // "₦246,000,000",
                      fontFamily: "",
                    ),
                    SizedBox(height: 20),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          "Buyer Price Per Ton",
                          style: kwikTextStlye(
                            12.0,
                            FontWeight.w300,
                            colorCodes.graniteGrey,
                          ),
                        ),
                        Text(
                          "Export Gross Earning",
                          style: kwikTextStlye(
                            12.0,
                            FontWeight.w300,
                            colorCodes.graniteGrey,
                          ),
                        ),
                      ],
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                            "\₦${NumberFormat('#,##0.00').format(widget.kwikticket.contract?.buyerSpecification?.buyerPricePerUnit)}",
                          // "${widget.kwikticket.contract?.buyerSpecification?.buyerPricePerUnit}",
                          style: kwikTextStlye(
                            14.0,
                            FontWeight.w600,
                            colorCodes.black,
                          ),
                        ),
                        Row(
                          children: [
                            Image.asset(
                              "assets/images/icons/Trending up.png",
                              height: 16,
                              width: 16,
                            ),
                            Text(
                                "${MoneyUtils.formatMoney(widget.kwikticket.projectedIncomeInDollars?.toString() ?? '0', symbol: '\$', decimalDigits: 2)}",
                              // "${widget.kwikticket.grossEarning}%",
                              style: kwikTextStlye(
                                14.0,
                                FontWeight.w600,
                                colorCodes.pigmentGreen,
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),

                    SizedBox(height: 20),

                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          "Destination",
                          style: kwikTextStlye(
                            12.0,
                            FontWeight.w300,
                            colorCodes.graniteGrey,
                          ),
                        ),
                        Text(
                          "Ticket Status",
                          style: kwikTextStlye(
                            12.0,
                            FontWeight.w300,
                            colorCodes.graniteGrey,
                          ),
                        ),
                      ],
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          widget.kwikticket.contract!.destinationCountry,
                          style: kwikTextStlye(
                            14.0,
                            FontWeight.w600,
                            colorCodes.black,
                          ),
                        ),
                        Container(
                          height: 24,
                          width: 64,
                          alignment: Alignment.center,
                          decoration: BoxDecoration(
                            border: Border.all(
                              width: 1.2,
                              color: HexColor("#FFAA33"),
                            ),
                            borderRadius: BorderRadius.circular(22),
                            color: HexColor("#FFAA33"),
                          ),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              // Image.asset(
                              //   "assets/images/icons/tick-circle.png",
                              //   height: 16,
                              //   width: 16,
                              // ),
                              Text(
                                "Non-active",
                                style: kwikTextStlye(
                                  10.0,
                                  FontWeight.w500,
                                  colorCodes.white,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                    SizedBox(height: 20),
                    contractDetailHeadingAndSubtitle(
                      "Contract Duration ",
                      "Deadline",
                      "${widget.kwikticket?.contract?.contractDuration} Months",

                      // "12 AUG 2025",
                      // "${widget.kwikticket.deadline.ho}"
                      // DateFormat('dd:h:mm').format(widget.kwikticket.deadline!),
                      DateFormat('dd MMM yyyy HH:mm').format(widget.kwikticket.deadline!),
                    ),
                  ],
                ),
              ),
              SizedBox(height: 24),
              kwikbutton("View Kwickticket", () {
                savePendingTicket(widget.kwikticket.uniqueId!);

                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder:
                        (context) =>
                            KwikticketScreen(kwikticket: widget.kwikticket),
                  ),
                );
                currentIndex = 3;
              }),
              SizedBox(height: 10),
              kwikbutton(
                '', //dud
                () {
                  _downloadReceipt(context);
                },
                textColor: colorCodes.textBlack,
                backgroundcolor: colorCodes.white,
                borderColor: colorCodes.antiFlashWhite,
                buttonChild: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      "Download",
                      style: kwikTextStlye(
                        16.0,
                        FontWeight.w500,
                        colorCodes.black,
                      ),
                    ),
                    Image.asset(
                      "assets/images/icons/direct-send.png",
                      height: 18,
                      width: 18,
                    ),
                  ],
                ),
              ),
              SizedBox(height: 80),
            ],
          ),
        ],
      ),
      bottomNavigationBar: Bottomnavigationbar(3),
    );
  }
}
